import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
	guides: [{ type: "autogenerated", dirName: "guides" }],
	chapters: [{ type: "autogenerated", dirName: "chapters" }],
	planets: [{ type: "autogenerated", dirName: "planets" }],
	index: [
		"intro",
		{ type: "link", label: "Guides", href: "guides/InfiniteLiquid" },
		{ type: "link", label: "Chapters", href: "chapters/ComingSoon" },
		{ type: "link", label: "Planets", href: "planets/ComingSoon" },
	],
};

export default sidebars;
